---
name: JIRA-Attachments-Rename
version: 1.02
author:
  - 'Martyloo <mlbright@gmail.com>'
abstract: This module renames JIRA attachments to match changed project keys
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  JIRA::Attachments::Rename:
    file: lib/JIRA/Attachments/Rename.pm
    version: 1.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
